### ISSUE TITLE
Unknown error

### ISSUE THREAD

**Issue by cr1t** [Azure/blobporter#114]
Getting this error when running blobporter we run it on other storage accounts but getting this and not sure what the issue is

BlobPorter
Copyright (c) Microsoft Corporation.
Version: 0.6.20
---------------

Files to Transfer (blob-blockblob) :
500 files. Total size:9133704871936
 -->   5 % [|........................] Committed Count: 0 Buffer Level: 100%panic: AddSumEvent failed the channel is closed or full

goroutine 610 [running]:
github.com/Azure/blobporter/internal.(*eventSink).AddSumEvent(0xc000032240, 0x2, 0x75d919, 0xc, 0x0, 0x0, 0x3ff0000000000000)
        /home/travis/gopath/src/github.com/Azure/blobporter/internal/eventsink.go:232 +0x1cb
github.com/Azure/blobporter/transfer.(*Worker).startWorker(0xc000206690, 0x7ba360, 0xc00027aac0)
        /home/travis/gopath/src/github.com/Azure/blobporter/transfer/worker.go:89 +0x80e
created by github.com/Azure/blobporter/transfer.(*Transfer).startWorkersAndCommitters
        /home/travis/gopath/src/github.com/Azure/blobporter/transfer/transfer.go:376 +0xae
Press any key to continue . . .

**Comment by giventocode** [comment]
Can you provide more details on what type of storage account you are targeting, and the number of files and their sizes?

**Comment by cr1t** [comment]
Hi

Its a StorageV2 account like the other accounts, I got it working by setting the handles_per_file to 1
