### ISSUE TITLE
Support Append Blob to Page Blob transfers when the source is not stored in a multiple of 512.

### ISSUE THREAD

**Issue by cheekp** [Azure/blobporter#115]
I'm looking to migrate 

From:
Azure. A container of Append Blobs within a Premium BlockBlobStorage account 

to:
Azure. Page Blobs in Premium StorageV2.

The source Append Blobs are of random sizes and not multiples of 512. I'm looking avoid the inherent 50K Appends per Blob limit by moving to page blobs. I now need to take my existing blobs with me.

When I run the tool

c:\Blobporter.exe -f "https://xxxxxxxx.blob.core.windows.net/sourcecontainer/" -c "sourcecontainer" -t blob-pageblob -b 4MB

I receive the following:

Invalid size for a page blob. The size of the file https:///xxxxxxxx.blob.core.windows.net/sourcecontainer .....(91522210) is not a multiple of 512.

Can anyone offer any guidance if/how I can achieve my objective with blobporter?

**Comment by giventocode** [comment]
Hi, thanks for your question. This is not a supported feature of blobporter.
