### ISSUE TITLE
Quiet mode (-q) please !

### ISSUE THREAD

**Issue by udf2457** [Azure/blobporter#49]
Hi,

Thank you for the wonderful blobporter tool. 

However its too noisy and verbose.  Please could you add a quiet mode flag so that the blobporter is more useful in scripts.

Please also consider making it less noisy by default and adding a verbose flag.

**Comment by giventocode** [comment]
Thank you for the valuable feedback!  

I will add a quite more (option) to the backlog for the new minor release.

**Comment by giventocode** [comment]
Quiet mode is now available in v.0.5.02
