### ISSUE TITLE
Content-MD5 please

### ISSUE THREAD

**Issue by udf2457** [Azure/blobporter#51]
Hi,

It would appear that blobporter does not calculate MD5 and set the Content-MD5 header option when uploading to Azure.

This means two things.... first, the Content-MD5 BLOB property has no value when the file is viewed in an Azure listing.

But perhaps more importantly, second, as per the Azure Documentation _"This hash is used to verify the integrity of the blob during transport. When this header is specified, the storage service checks the hash that has arrived with the one that was sent."_

It is therefore a fairly important thing.

**Comment by giventocode** [comment]
Thanks for the feedback. This feature will be included in the next minor release.

**Comment by giventocode** [comment]
Block level MD5 can be computed in v.0.5.02

**Comment by udf2457** [comment]
Sorry to re-open this but "-m" does not appear to be working as advertised ?

```
$ blobporter -q -m -c test -f a -n test
BlobPorter 
Copyright (c) Microsoft Corporation. 
Version: 0.5.02
---------------
Transfer Task: file-blockblob
Files to Transfer:
Source: a Size:2 

The process took 124.574686ms to run.
Throughput: 0.00 MB/s (0.00 Mb/s) 
Configuration: R=24, W=36, DataSize=2KiB (2), Blocks=1
Cumulative Writes Duration: Total=28.659118ms, Avg Per Worker=796.086µs
Retries: Avg=0 Total=0
```

Yields:

`<?xml version="1.0" encoding="utf-8"?><EnumerationResults ServiceEndpoint="https://my***account.blob.core.windows.net/" ContainerName="test"><Blobs><Blob><Name>test</Name><Properties><Last-Modified>Sat, 13 May 2017 09:10:33 GMT</Last-Modified><Etag>0x8D499DFE8F46B23</Etag><Content-Length>2</Content-Length><Content-Type>application/octet-stream</Content-Type><Content-Encoding /><Content-Language /><Content-MD5 /><Cache-Control /><Content-Disposition /><BlobType>BlockBlob</BlobType><LeaseStatus>unlocked</LeaseStatus><LeaseState>available</LeaseState></Properties></Blob></Blobs><NextMarker /></EnumerationResults>`

As you can see, the `Content-MD5` element is empty, which would not be the case if you were really sending MD5s ....
