### ISSUE TITLE
Overwrite Existing blob

### ISSUE THREAD

**Issue by jkergosi** [Azure/blobporter#73]
Can we have an command option that allows overwrite of an existing blob file if one exists?
ex. 
-o, force overwrite

Thoughts?

**Comment by giventocode** [comment]
Overwriting existing blobs is the default behavior. Are you seeing something different? Can you provide more details?

**Comment by jkergosi** [comment]
I realized that it was Azure. It is marking my blobs as leased and not letting them be overwritten.
