### ISSUE TITLE
Upload fails with "Empty files are not supported <directory name>"

### ISSUE THREAD

**Issue by seguler** [Azure/blobporter#81]
100K_1 is a directory, and blobporter thinks it is an empty file failing the transfer. Even if this was an empty file, the transfer should not fail. Anyone can have empty files in a filesystem.

C:\Users\seguler>blobporter -c migrate2 -f "F:\dir1\*"
BlobPorter
Copyright (c) Microsoft Corporation.
Version: 0.5.25
---------------
2018/02/04 18:18:24 Empty files are not allowed. The file F:\dir1\100K_1 is empty

**Comment by giventocode** [comment]
Empty folders don't have an equivalent in blob storage.  The error message needs to be clearer about the fact that empty folders are not allowed.  Now, you bring another suggestion. Currently empty files are not allowed as there are some assumptions in the control process that are impacted when they are present in a transfer.

**Comment by giventocode** [comment]
Closing this issue as now is tracked in two issues #84 and #83
